name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install dependencies
        run: |
          npm i
      - name: Run test
        run: |
          npm test
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          script: |
            cd /home/efiand/efiand.ru
            git pull --rebase
            npm ci
            npm run build
